### ISSUE TITLE
Document server ports of different services

### ISSUE THREAD

**Issue by htdvisser** [packetbroker/api#11]
#### Summary

It would be good to document the default ports, and perhaps even addresses on which the different services are exposed.

#### Why do we need this?

The APIs aren't exposed on the standard HTTPS port, so developers need to know where the services are exposed. Documenting it here would save developers some time guessing or digging through the reference implementation of the clients.

#### What is already there? What do you see now?

The default ports are buried in the reference implementation of the clients (https://github.com/packetbroker/pb). The (staging) address is mentioned in the README of that repository.

#### What is missing? What do you want to see?

This information should probably be part of the API documentation.

#### Can you do this yourself and submit a Pull Request?

Sure

**Comment by johanstokking** [comment]
Closed by https://github.com/packetbroker/api/commit/63a3d8d77d23e22b38f34b338b3873ced43b5113
